version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"  # Assurez-vous de spécifier la version correcte de Python

sphinx:
  configuration: docs/conf.py  # Si vous utilisez Sphinx pour générer la documentation

python:
  install:
    requirements: requirements.txt  # Spécifie le fichier requirements.txt pour installer les dépendances
