version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/conf.py  # Le chemin vers votre fichier de configuration Sphinx

python:
  install:
    - requirements.txt

